name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Get Node.js Version
        run: |
          echo "$(cat ./package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV
      - name: Use Node.js ${{ env.NodeVersion }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ env.NodeVersion }}
          cache: 'npm'
      - name: Run npm clean-install
        run: npm ci
      - name: Check Prettier
        run: npm run prettier
      - name: Check ESLint
        run: npm run lint:sonar
      - name: LWC Unit Tests
        run: npm run test:unit:coverage
